#Feature: Client management module - Basic info tab
#  Scenario: Verify that the user is able to loggedin and redirected to client module
#    Given user is on the login page
#    When user enters the credentials
#    And click on the login
#    Then user is logged to dashboard page
#    When user clicks on the client module menu in side nav bar
#    Then user will be directed to client module page
#
#  Scenario: Verify that the user is able to directed to basic details tab when add client button is clicked
#    Given user is on the client list page
#    When user clicks on the add client button
#    Then user is redirected to client page basic details tab
#
#  Scenario: Verify that the user is able to enter the client name, get the client id autogenerated
#    Given user is on the client basic details tab
#    When user enter the client name
#    Then the client id is automatically fetched
#
#  Scenario: Verify that the user is able to select the client type, country, tax type and enter tax id
#    Given user is on the client basic details tab
#    When user selects the client type, country, enter tax id
#    Then select tax category
#
#  Scenario: Verify that the user is able to select industry type, enter website and email
#    Given user is on the client basic details tab
#    When user selects the industry type
#    And enters the website and email name
#
#  Scenario: Verify that the user is able to select the country code and type the number in telephone, mobile and fax number field
#    Given user is on the client basic details tab
#    When user selects the country code
#    And type the telephone number
#    Then type the mobile number, fax number
#
#  Scenario: Verify that the user is able to get the contract signed details while cliking on yes only
#    Given user is on the client basic details tab
#    When user checks the checkbox to yes
#    Then the user will get the contract details to be filled
#
#  Scenario: Verify that the user should not get the contract details field by clicking on no
#    Given user is on the client basic details tab
#    When user checks the checkbox to no
#    Then the user should not get the contract details
#
#  Scenario: Verify that the user is able to enter contract title, start date, end date, description and attach the contract document
#    Given user is on the client basic details tab
#    When user enters contract title, start date, end date, description
#    Then user will attach the contract document in the attachment
#
#  Scenario: Verify that the user is able to add extra contract details by clicking on the add icon
#    Given user is on the client basic details tab
#    When user clicks on the add icon
#    Then user will get the another set of contract adding section
#
#  Scenario: Verify that the user is able to enter the company address by adding the address title, address type
#    Given user is on the client basic details tab
#    When user enters the address title
#    And user selectes the address type
#
#  Scenario: Verify that the user is able to add address lines and add the extra address lines by clicking on addd icon there
#    Given user is on the client basic details tab
#    When user enters the address line
#    And clicks on the add icon to add the extra address lines
#
#  Scenario: Verify that the user is able to select the country, state and city, enters postal code
#    Given user is on the client basic details tab
#    When user selects the country, state, city
#    Then user enters the postal code
#
#  Scenario: Verify that the user is able to made the entered address as primary billing and shipping address by checking the checkbox respectively
#    Given user is on the client basic details tab
#    When user selects the primary billing address checkbox
#    Then the address will made into billing address
#    And user selects the primary shipping address checkbox
#    Then user will get the address as primary shipping address
#
#  Scenario: Verify that the user is able to save the entered details then it will be viewed in the table
#    Given user is on the client basic details tab
#    When user clicks on the save button
#    Then the client basic detail will be added to the client list table
#
#  Scenario: Verify that the user is able to get the save the details without filling both tax id and tax category
#    Given user is on the client basic details tab
#    When user clicks on submit without entering both tax id and tax category
#    Then user wants to submit it successfully
#
#  Scenario: Verify that the user is able to get the mandatory and validation error message for client name field
#    Given user is on the client basic details tab
#    When user clicks on save without entering in client name
#    Then user wants to get the mandatory error message for client name field
#    And user enters the input other than text
#    Then user wants to get the validation error message for client name field
#
#  Scenario: Verify that the user is able to get the mandatory error message for client type, country dropdowns
#    Given user is on the client basic details tab
#    When user clicks on save without selecting client type and country
#    Then user wants to get the error message for client type, country dropdown
#
#  Scenario: Verify that the user is able to get the mandatory error message for tax category only the tax id is typed
#    Given user is on the client basic details tab
#    When user enters the tax id
#    And clicks on save button without giving the tax category
#    Then user wants to get mandatory error message for tax category
#
#  Scenario: Verify that the user is able to get the mandatory and validation error message for industry type dropdown and email  field
#    Given user is on the client basic details tab
#    When user clicks on save without entering in industry type, email
#    Then user wants to get the mandatory error message for industry type, email field
#    And user enters the invalid email format
#    Then user wants to get the validation error message for invalid email
#
#  Scenario: Verify that the user is able to get the mandatory and validation error message for telephone, mobile and fax number field
#    Given user is on the client basic details tab
#    When user clicks on save without entering in telephone, mobile number
#    Then user wants to get the mandatory error message for telephone, mobile number field
#    And user enters the input other than number
#    Then user wants to get the validation error message for telephone, mobile number field
#
#  Scenario: Verify that the user is able to get the mandatory error message for contract signed radio button
#    Given user is on the client basic details tab
#    When user clicks on save without selecting the radio button for contract signed
#    Then user wants to get the mandatory error message for contract signed radio button
#
#  Scenario: Verify that the user is able to get the mandatory and validation error message for contract title, start date, end date, attachment field
#    Given user is on the client basic details tab
#    When user clicks on save without entering in contract title, start date, end date, attachment
#    Then user wants to get the mandatory error message for contract title, start date, end date, attachment field
#    And user enters input other that alphanumeric values in contract title
#    Then user wants to get validation error message for contract title field
#
#  Scenario: Verify that the user is able to get the mandatory and validation error message for address title, address type field
#    Given user is on the client basic details tab
#    When user clicks on save without entering address title and address type
#    Then user wants to get the mandatory error message for address title and address type field
#    And user enters input other than alphanumeric values in address title
#    Then user wants to get validation error message for address title field
#
#  Scenario: Verify that the user is able to get the mandatory error message for address line 1, address line 2, address line 3
#    Given user is on the client basic details tab
#    When user clicks on save without entering address line 1, address line 2, address line 3
#    Then user wants to get the mandatory error message for address line 1, address line 2, address line 3 field
#
#  Scenario: Verify that the user is able to get the mandatory error message for country, state, city, postal code
#    Given user is on the client basic details tab
#    When user clicks on save without entering country, state, city, postalcode
#    Then user wants to get the mandatory error message for country, state, city, postalcode
#    And user enters input other than numeric values in postalcode
#    Then user wants to get validation error message for postalcode field
#
#  Scenario: Verify that the user is able to search the client by giving the keywords in the search bar
#    Given user is on the client list page
#    When user enters the search keywords
#    Then user wants to get the result regarding to the search
#
#  Scenario: Verify that the user is able to get the message displayed when there is no result for the searched keywords
#    Given user is on the client list page
#    When user enters the search keywords which is not there in the table
#    Then user will get the no data found message inside the table
#
#  Scenario: Verify that the user is able to seach by client name by selecting the client name in dropdown
#    Given user is on the client list page
#    When user selects the client name
#    Then user will get the selected client name in the list
#
#  Scenario: Verify that the user is able to search by client type by selecting the client type from the dropdown
#    Given user is on the client list page
#    When user selects the client type
#    Then user will get the selected client type in the list
#
#  Scenario: Verify that the user is able to clear the applied filter by clicking on the reset button
#    Given user is on the client list page
#    When user clicks on the reset button
#    Then filter fields will become empty
#
#  Scenario: Verify that the user is able to delete the client by clicking the checkbox in the list
#    Given user is on the client list page
#    When user clicks on checkbox in the list
#    And clicks ln the delete button
#    Then the confiration pop-up for delete will appear
#    And the user clicks on yes
#    Then the client will be deleted from the list
#
#  Scenario: Verify that the user is able to change the table settings by clicking on the table icon
#    Given user is on the client list page
#    When user clicks on the table settings
#    Then user will get the pop-up of columns in the list
#    And the user select or deselect the column name
#    And click on apply button
#    Then the list will be edited regarding the column changes
#
#  Scenario: Verify that the user is able to print the table by clicking the print icon
#    Given user is on the client list page
#    When user clicks on the print icon
#    Then user will get the pop-up for print to print the table
#
#  Scenario: Verify that the user is able to download the list by clicking on the download icon
#    Given user is on the client list page
#    When user clicks on the download icon
#    Then it will download all the data in the table
#
#  Scenario: Verify that the user is able to download the selectd client details from the table
#    Given user is on the client list page
#    When user clicks on the checkbox
#    And clicks on download icon
#    Then user will get the selected clients detail downloaded
#
#  Scenario: Verify that the user is able to download the filtered client details from the table
#    Given user is on the client list page
#    When user apply the filters
#    And click on the download icon
#    Then user will get the applied filter client details
#
#  Scenario: Verify that the user is able to sort the table data's by clicking on the arrow in the table header
#    Given user is on the client list page
#    When user clicks on the arrow in the table header
#    Then the data will be sorted
#
#  Scenario: Verify that the user is able to active or inactive the client by toggling the button
#    Given user is on the client list page
#    When user toggle the button to active or inactive
#    Then the client will activated or inactivated
#
#  Scenario: Verify that the user is able to view the added client details by clicking the client name in the table
#    Given user is on the client list page
#    When user clicks on the client name in the table
#    Then user will be redirected to the client view page
#    And all the details will be fetched