Feature: Inventory module
  Scenario: Verify that the user is able to loggedin and redirected to inventory module
    Given user is on the login page
    When user enters the credentials
    And click on the login
    Then user is logged to dashboard page
    When user clicks on the inventory module menu in side nav bar
    Then user will be directed to inventory module page

  Scenario: Verify that the user is able to directed to item creation page when new item button is clicked
    Given user is on the inventory module page
    When user clicks on the new item button
    Then user is redirected to item adding page

  Scenario: Verify that the user is able to add itemname, item type and get sku, item id automatically in the new item page
    Given user is on the item creation page
    When user enters itemname, select item type
    And SKU, item id will be autogenerated

  Scenario: Verify that the user is able to select supplier, unit and enter costprice in the new item page
    Given user is on the item creation page
    When user selects supplier, unit
    And enter costprice in that field

  Scenario: Verify that the user is able to add the unit price by clicking the add icon and entering the details
    Given user is on the new item page
    When user clicks on the add icon in the page
    Then user will get the pop-up to enter unit details
    And the user enters the details
    Then click on add to get the unit in the dropdown

  Scenario: Verify that the user is able to add the dimensions and weight in the new item page
    Given user is on the new item page
    When user enters the length, width, height
    And enters the weight in that field
    Then selects the unit for both fields

  Scenario: Verify that the user is able to enter reorder level, stock limit, selling price
    Given user is on the new item page
    When user enters the reorder level, stock limit
    Then user enters the selling price

  Scenario: Verify that the user is able to enter the description, check the returnable item checkbox
    Given user is on the new item page
    When user enter the description
    And click the returnable item checkbox

  Scenario: Verify that the user is able to add item image in an attachment and also get the attached image as an pop-up
    Given user is on the new item page
    When user clicks on the attachment icon
    And attaches the image
    Then user is abe to get the list of imaged attched below the field
    And user clicks on the image it will give a pop-up of that clicked image

  Scenario: Verify that after all the details are filled and clicked on save button then the item will be added to the dropdown in the program page
    Given user is on the new item page
    When user enters all the details
    And clicks on save button
    Then the item added will be displayed in the list

  Scenario: Verify that the user is able to get the mandatory error messages for item name, item type, unit
    Given user is on the new item page
    When user clicks on save button without entering item name, item type, unit
    Then user will get the mandatory error message for item name, item type, unit fields

  Scenario: Verify that the user is able to get the mandatory error messages for cost price, weight, reorder level, selling price
    Given user is on the new item page
    When user clicks on save button without entering cost price, weight, reorder level, selling price
    Then user will get the mandatory error message for cost price, weight, reorder level, selling price fields

  Scenario: Verify that the user is able to get the validation error message for item name, SKU, Item id
    Given user is on the new item page
    When user enters other than alphanumeric in the item name
    Then user will get the validation error message for item name
    And SKU, Item id needs to be in alphanumeric if it is other than alphanumeric

  Scenario: Verify that the user is able to get the validation error message for cost price, selling price, dimensions, weight, reorder level, stock limit
    Given user is on the new item page
    When user enters other than numbers in the cost price, selling price, dimensions, weight, reorder level, stock limit
    Then user will get the validation error message for cost price, selling price, dimensions, weight, reorder level, stock limit fields

  Scenario: Verify that the user is able to search the program by giving the keywords in the search bar
    Given user is on the inventory page
    When user enters the search keywords
    Then user wants to get the result regarding to the search

  Scenario: Verify that the user is able to get the message displayed when there is no result for the searched keywords
    Given user is on the inventory page
    When user enters the search keywords which is not there in the table
    Then user wants to get the no data found message inside the table

  Scenario: Verify that the user is able to get all the items displayed when the all in the stock level is clicked
    Given user is on the inventory page
    When the user clicks all in the stock level
    Then all items will be displayed

  Scenario: Verify that the user is able to get all the items displayed when the low in the stock level is clicked
    Given user is on the inventory page
    When the user clicks low in the stock level
    Then lower count items will be displayed

  Scenario: Verify that the user is able to get all the items displayed when the expired in the stock level is clicked
    Given user is on the inventory page
    When the user clicks expired in the stock level
    Then expired items will be displayed

  Scenario: Verify that the user is able to seach by supplier by selecting the supplier name in dropdown
    Given user is on the inventory page
    When user selects the supplier
    Then user will get the selected supplier in the list will be displayed

  Scenario: Verify that the user is able to search by item type by selecting the from the dropdown
    Given user is on the inventory page
    When user selects the item type
    Then user will get the selected item in the list

  Scenario: Verify that the user is able to clear the applied filter by clicking on the reset button
    Given user is on the inventory page
    When user clicks on the reset button
    Then filter fields will become empty

  Scenario: Verify that the user is able to delete the item by clicking the checkbox in the list
    Given user is on the inventory page
    When user clicks on checkbox in the list
    And clicks ln the delete button
    Then the confiration pop-up for delete will appear
    And the user clicks on yes
    Then the client will be deleted from the list

  Scenario: Verify that the user is able to change the table settings by clicking on the table icon
    Given user is on the inventory page
    When user clicks on the table settings
    Then user will get the pop-up of columns in the list
    And the user select or deselect the column name
    And click on apply button
    Then the list will be edited regarding the column changes

  Scenario: Verify that the user is able to print the table by clicking the print icon
    Given user is on the inventory page
    When user clicks on the print icon
    Then user will get the pop-up for print to print the table

  Scenario: Verify that the user is able to download the list by clicking on the download icon
    Given user is on the inventory page
    When user clicks on the download icon
    Then it will download all the data in the table

  Scenario: Verify that the user is able to download the selected item details from the table
    Given user is on the inventory page
    When user clicks on the checkbox
    And clicks on download icon
    Then user will get the selected item detail downloaded

  Scenario: Verify that the user is able to download the filtered item details from the table
    Given user is on the inventory page
    When user apply the filters
    And click on the download icon
    Then user will get the applied filter item details

  Scenario: Verify that the user is able to sort the table data's by clicking on the arrow in the table header
    Given user is on the inventory page
    When user clicks on the arrow in the table header
    Then the data will be sorted

  Scenario: Verify that the user is able to view the added item by clicking the item name
    Given user is on the inventory page
    When user clicks on item name
    Then user will be able to view the added details

  Scenario: Verify that the user is able to edit the item details by clicking on the view page fields
    Given user is on the view item page
    When user clicks on the item fields
    Then user will get the save and cancel button
    And after edited any details
    Then user clicks on the save button in edit page
    And user will get the pop-up of update confirmation
    Then user will get the updated successfully message

  Scenario: Verify that the user is able to redirected to item list pahe while clicking on cancel button
    Given user is on the view item page
    When user clicks on the cancel button
    Then user will be redirected to item list page