Feature: Program creation module
  Scenario: Verify that the user is able to loggedin and redirected to program module
    Given user is on the login page
    When user enters the credentials
    And click on the login
    Then user is logged to dashboard page
    When user clicks on the program module menu in side nav bar
    Then user will be directed to program module page

  Scenario: Verify that the user is able to directed to program creation page when create program button is clicked
    Given user is on the program menu
    When user clicks on the add program button
    Then user is redirected to program adding page
    And clicks on create program in that page
    Then user is redirected to program creation page

  Scenario: Verify that the user is able to enter the program name, get the program id autogenerated
    Given user is on the program adding page
    When user enter the program name
    Then the program id is automatically fetched

  Scenario: Verify that the user is able to get the program value automatically by calculating the selling price of the mentioned items in the table
    Given user is on the program adding page
    When user clicks on the dropdown inside the item name table column
    And selects the item from the dropdown
    Then user will get all the details automatically fetched
    And the program value will be displayed based on the items selling price displayed in the table

  Scenario: Verify that the user is able to map item for the program creating
    Given user is on the program adding page
    When user selects the item from the dropdown in the item name table column
    Then all the details of the item will be fetched in the table automatically
    And after selected the first item name
    Then the user will get the another row for adding another item
    And click on save button to map the added item to the program creating

  Scenario: Verify that the user is able to redirected to item add page to create an new item that was not in the item name dropdown
    Given user is on the program adding page
    When user clicks on the create item button
    Then user will be redirected to item adding page

  Scenario: Verify that the user is able to add itemname, item type and get sku, item id automatically in the new item page
    Given user is on the new item page
    When user enters itemname, select item type
    And SKU, item id will be autogenerated

  Scenario: Verify that the user is able to select supplier, unit and enter costprice in the new item page
    Given user is on the new item page
    When user selects supplier, unit
    And enter costprice in that field

  Scenario: Verify that the user is able to add the unit price by clicking the add icon and entering the details
    Given user is on the new item page
    When user clicks on the add icon in the page
    Then user will get the pop-up to enter unit details
    And the user enters the details
    Then click on add to get the unit in the dropdown

  Scenario: Verify that the user is able to add the dimensions and weight in the new item page
    Given user is on the new item page
    When user enters the length, width, height
    And enters the weight in that field
    Then selects the unit for both fields

  Scenario: Verify that the user is able to enter reorder level, stock limit, selling price
    Given user is on the new item page
    When user enters the reorder level, stock limit
    Then user enters the selling price

  Scenario: Verify that the user is able to enter the description, check the returnable item checkbox
    Given user is on the new item page
    When user enter the description
    And click the returnable item checkbox

  Scenario: Verify that the user is able to add item image in an attachment and also get the attached image as an pop-up
    Given user is on the new item page
    When user clicks on the attachment icon
    And attaches the image
    Then user is abe to get the list of imaged attched below the field
    And user clicks on the image it will give a pop-up of that clicked image

  Scenario: Verify that after all the details are filled and clicked on save button then the item will be added to the dropdown in the program page
    Given user is on the new item page
    When user enters all the details
    And clicks on save button
    Then the page will be redirected to program creation page
    And if the user clicks on the item name dropdown
    Then the item added will be displayed

  Scenario: Verify that the user is able to get the mandatory error messages for item name, item type, unit
    Given user is on the new item page
    When user clicks on save button without entering item name, item type, unit
    Then user will get the mandatory error message for item name, item type, unit fields

  Scenario: Verify that the user is able to get the mandatory error messages for cost price, weight, reorder level, selling price
    Given user is on the new item page
    When user clicks on save button without entering cost price, weight, reorder level, selling price
    Then user will get the mandatory error message for cost price, weight, reorder level, selling price fields

  Scenario: Verify that the user is able to get the validation error message for item name, SKU, Item id
    Given user is on the new item page
    When user enters other than alphanumeric in the item name
    Then user will get the validation error message for item name
    And SKU, Item id needs to be in alphanumeric if it is other than alphanumeric
    Then user will get the validation error message

  Scenario: Verify that the user is able to get the validation error message for cost price, selling price, dimensions, weight, reorder level, stock limit
    Given user is on the new item page
    When user enters other than numbers in the cost price, selling price, dimensions, weight, reorder level, stock limit
    Then user will get the validation error message for cost price, selling price, dimensions, weight, reorder level, stock limit fields

  Scenario: Verify that the user is able to delete the items by clicking the checkbox in the list
    Given user is on the program adding page
    When user clicks on checkbox in the list
    And clicks ln the delete button
    Then the confiration pop-up for delete will appear
    And the user clicks on yes
    Then the item will be deleted from the list

  Scenario: Verify that the user is able to make the items active or inactive for the program
    Given user is on the program adding page
    When user toggle the button on
    Then the item will be mapped to that program
    When user toggle the button off
    Then the item will not be mapped

  Scenario: Verify that the user is able to sort the item table data's by clicking on the arrow in the table header
    Given user is on the program adding page
    When user clicks on the arrow in the table header
    Then the data will be sorted

  Scenario: Verify that the saved program will be displayed in the program list after saving the details
    Given user is on the program adding page
    When user add all the details needed
    Then user will get the program displayed in the program list table

  Scenario: Verify that the user is able to search the program by giving the keywords in the search bar
    Given user is on the program list page
    When user enters the search keywords
    Then user wants to get the result regarding to the search

  Scenario: Verify that the user is able to get the message displayed when there is no result for the searched keywords
    Given user is on the program list page
    When user enters the search keywords which is not there in the table
    Then user wants to get the no data found message inside the table

  Scenario: Verify that the user is able to seach by client name by selecting the client name in dropdown
    Given user is on the program list page
    When user selects the client name
    Then user will get the selected client name in the list

  Scenario: Verify that the user is able to search by item by selecting the from the dropdown
    Given user is on the program list page
    When user selects the item
    Then user will get the selected item in the list

  Scenario: Verify that the user is able to clear the applied filter by clicking on the reset button
    Given user is on the program list page
    When user clicks on the reset button
    Then filter fields will become empty

  Scenario: Verify that the user is able to delete the items by clicking the checkbox in the list
    Given user is on the program list page
    When user clicks on checkbox in the list in program table
    And clicks ln the delete button in program list page
    Then the confiration pop-up for delete will appear in program list page
    And the user clicks on yes in the pop-up
    Then the program will be deleted from the list

  Scenario: Verify that the user is able to make the program active or inactive for the program
    Given user is on the program list page
    When user toggle the button on in program table
    Then the program will be mapped
    When user toggle the button off in program table
    Then the program will not be mapped

  Scenario: Verify that the user is able to change the table settings by clicking on the table icon
    Given user is on the program list page
    When user clicks on the table settings
    Then user will get the pop-up of columns in the list
    And the user select or deselect the column name
    And click on apply button
    Then the list will be edited regarding the column changes

  Scenario: Verify that the user is able to print the table by clicking the print icon
    Given user is on the program list page
    When user clicks on the print icon
    Then user will get the pop-up for print to print the table

  Scenario: Verify that the user is able to download the list by clicking on the download icon
    Given user is on the program list page
    When user clicks on the download icon
    Then it will download all the data's in the table

  Scenario: Verify that the user is able to download the selectd program details from the table
    Given user is on the program list page
    When user clicks on the checkbox
    And clicks on download icon
    Then user will get the selected program detail downloaded

  Scenario: Verify that the user is able to download the filtered program details from the table
    Given user is on the program list page
    When user apply the filters
    And click on the download icon
    Then user will get the applied filter program details

